version: "3.9"
services:
  backend:
    build: ./backend
    container_name: gcs-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: nestuser
      DATABASE_PASSWORD: nestpass
      DATABASE_NAME: nestdb
      CHOKIDAR_USEPOLLING: true  
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules   
    command: npm run start:dev

  frontend:
    build: ./frontend
    container_name: gcs-frontend
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules   
    command: npm run dev -- --hostname 0.0.0.0 --port 3000

  db:
      image: mysql:8.0
      container_name: gcs-db
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: nestdb
        MYSQL_USER: nestuser
        MYSQL_PASSWORD: nestpass
      ports:
        - "3307:3306"
      command: [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
      volumes:
        - mysql_data:/var/lib/mysql
        - ./db/init:/docker-entrypoint-initdb.d
volumes:
  mysql_data:
